# Generated by Django 4.2.9 on 2024-01-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0002_alter_rango_nombre_alter_tipo_mantenimiento_nombre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlotaVehicular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('chasis', models.CharField(max_length=30, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('motor', models.CharField(max_length=20)),
                ('kilometraje', models.CharField(max_length=20)),
                ('cilindraje', models.CharField(max_length=20)),
                ('capacidad_carga', models.CharField(max_length=20)),
                ('capacidad_pasajeros', models.CharField(max_length=20)),
                ('tipovehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.tipo_vehiculo')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Flota Vehicular',
                'unique_together': {('placa', 'chasis')},
            },
        ),
    ]
