# Generated by Django 4.2.9 on 2024-03-22 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movilizacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movilizacion',
            options={'verbose_name_plural': 'Movilizacioness'},
        ),
    ]
